version: '3'

services:
  api-server:
    container_name: api-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    networks:
      - sorok-networks
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=sorok
    depends_on:
      - api-server
    restart: always
    networks:
      - sorok-networks
  # volumne 설정 추가

networks:
  sorok-networks:
