spring:
  profiles:
    active: ${active}

  output:
    ansi:
      enabled: always

jwt:
  secret: rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345
  validateTimeMS: 1800000

# springdoc.api-docs.path=/api-docs
springdoc:
  api-docs:
    path: /api-docs

# springdoc.swagger-ui.path=/swagger-ui-custom.html
  swagger-ui:
    path: /swagger-ui.html

# db username, password ? ??? ?? and application.yml local, prod ??? ?? ?? ??