spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:local
    username: sa
    driverClassName: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
